
import { useState, useEffect } from 'react';
import { supabase } from '../../../../lib/supabaseClient';
import { GoalDetail, GoalWithIntelligence, IntelligenceMatrix, StrategyStatus } from '../types';

export const useGoalIntelligence = () => {
    const [goals, setGoals] = useState<GoalWithIntelligence[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [topExpenseCategory, setTopExpenseCategory] = useState<string | null>(null);

    // Helper to fetch top expense category
    const fetchTopExpense = async () => {
        try {
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) return;

            // Simple aggregation to find top expense category (Last 30 days)
            const oneMonthAgo = new Date();
            oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1);

            const { data } = await supabase
                .from('transacciones')
                .select('categoria, cantidad')
                .eq('user_id', user.id)
                .eq('pilar', 'Gastar')
                .gte('fecha', oneMonthAgo.toISOString());

            if (data && data.length > 0) {
                const totals: Record<string, number> = {};
                data.forEach((t: any) => {
                    totals[t.categoria] = (totals[t.categoria] || 0) + t.cantidad;
                });
                const sorted = Object.entries(totals).sort((a, b) => b[1] - a[1]);
                if (sorted.length > 0) {
                    setTopExpenseCategory(sorted[0][0]);
                }
            }
        } catch (e) {
            console.error("Error fetching top expense:", e);
        }
    };

    const calculateIntelligence = (goal: GoalDetail): IntelligenceMatrix => {
        const {
            monto_objetivo,
            monto_actual,
            promedio_ingresos_mensual,
            promedio_gastos_mensual,
            capacidad_neta_disponible,
            aporte_planeado_inversion,
            aporte_planeado_total
        } = goal;

        // 1. COMBUSTIBLE (Fuel): Validity of the Plan
        // Compare Net Capacity for THIS goal vs The Promise for THIS goal
        let fuelScore = 100;
        const gap = capacidad_neta_disponible - aporte_planeado_total;

        if (aporte_planeado_total > 0) {
            fuelScore = Math.min(100, Math.max(0, (capacidad_neta_disponible / aporte_planeado_total) * 100));
        } else if (capacidad_neta_disponible <= 0) {
            fuelScore = 0;
        }

        const combustible = Math.round(fuelScore);

        // 2. FRICCIÓN (Friction): Expense Drag
        const frictionRaw = promedio_ingresos_mensual > 0
            ? (promedio_gastos_mensual / promedio_ingresos_mensual) * 100
            : 100;
        const friccion = Math.min(100, Math.max(0, frictionRaw));

        // 3. ACELERADOR (Accelerator) - ROCKET 🚀 & SNAIL 🐌
        const remainingAmount = Math.max(0, monto_objetivo - monto_actual);

        // Scenario A: Snail (Reality Check)
        // How much of my REAL NET capacity can I give to this goal?
        // Logic: Cap it at my real net available. If I promise 1000 but only have 600, Snail moves at 600.
        let effectiveMonthlyCapacity = 0;
        if (aporte_planeado_total > 0) {
            // El Snail se mueve usando SOLO la capacidad neta real que tengo disponible como máximo
            effectiveMonthlyCapacity = Math.min(Math.max(0, capacidad_neta_disponible), aporte_planeado_total);
        } else if (capacidad_neta_disponible > 0) {
            // If no plan, assume full net capacity to show "potential"
            effectiveMonthlyCapacity = capacidad_neta_disponible;
        }

        let currentMonths = 999;
        if (effectiveMonthlyCapacity > 0) {
            currentMonths = Math.ceil(remainingAmount / effectiveMonthlyCapacity);
        } else {
            // Si la capacidad es 0 o negativa (CRITICAL), la ruta está bloqueada
            currentMonths = 999;
        }

        // Scenario B: Rocket (Optimized/Planned Investment)
        // Uses 'aporte_planeado_inversion' with Compound Interest (8% E.A.)
        const r = 0.08 / 12; // Monthly rate
        let optimizedMonths = 999;
        const totalMonthlyPlan = aporte_planeado_total; // Ahorro + Inversión

        if (totalMonthlyPlan > 0) {
            let n = 0;
            let fv = monto_actual;
            // We iterate assuming user FULFILLS the plan
            while (fv < monto_objetivo && n < 600) {
                n++;
                fv += totalMonthlyPlan;
                // Yield only on the Investment portion (Accumulated)
                // Approximation: The pool of money generated by 'Inversion' contributions grows at 8%.
                // Interest = (Current FV * Rate) * (Inversion Contribution / Total Contribution)
                const ratio = aporte_planeado_inversion / totalMonthlyPlan;
                fv += (fv * r * ratio);
            }
            optimizedMonths = n;
        }

        const timeSaved = Math.max(0, currentMonths - optimizedMonths);

        // 4. ESTADO (Status) & RECOMMENDATION
        let estado: StrategyStatus = 'ON_TRACK';
        let recomendacion = 'Tu plan es sostenible.';

        const deficit = Math.abs(gap);
        const tolerance = Math.max(0, capacidad_neta_disponible) * 0.20; // 20% margin

        if (gap < 0) {
            if (capacidad_neta_disponible <= 0) {
                // Completely out of net capacity
                estado = 'CRITICAL';
                recomendacion = `¡Alerta! No tienes capacidad neta disponible para cubrir esta meta ($${aporte_planeado_total.toLocaleString()}). Recorta gastos en "${topExpenseCategory || 'Gastos Varios'}".`;
            } else if (deficit <= tolerance) {
                // Inside the 20% tolerance margin
                estado = 'ON_TRACK';
                recomendacion = `Margen Estrecho. Estás aportando un ${Math.round((deficit / capacidad_neta_disponible) * 100)}% por encima de tu capacidad neta promedio.`;
            } else {
                // Aggressive Plan!
                estado = 'AGGRESSIVE_PLAN';
                recomendacion = `Plan Agresivo. El aporte supera tu capacidad neta libre en $${deficit.toLocaleString()}. Sacrifica gastos o aumenta ingresos para cumplir este reto.`;
            }
        } else if (friccion > 90) {
            estado = 'AT_RISK';
            recomendacion = `Tus gastos fijos son elevadísimos (${Math.round(friccion)}%). Cualquier imprevisto puede romper tu liquidez neta.`;
        } else if (aporte_planeado_inversion > 0 && timeSaved > 3) {
            estado = 'OPTIMIZED';
            recomendacion = `Excelente. Tu estructura incluye inversión, lo que acelera el proceso ${timeSaved} meses gracias al interés compuesto.`;
        } else if (aporte_planeado_total <= 0) {
            estado = 'AT_RISK';
            recomendacion = "No has definido un aporte. Edita la meta para fijar la periodicidad y comprometer un hábito.";
        }

        // Data Quality Warning
        let dataQualityWarning: string | undefined;
        if (promedio_gastos_mensual <= 0) {
            dataQualityWarning = "⚠️ Faltan datos de gastos. La 'Capacidad Real' puede ser inexacta.";
        }

        return {
            combustible,
            friccion,
            acelerador: {
                proyeccion_actual_meses: currentMonths,
                proyeccion_optimizada_meses: optimizedMonths,
                ahorro_tiempo_meses: timeSaved
            },
            estado,
            recomendacion_clave: recomendacion,
            dataQualityWarning
        };
    };

    const fetchGoals = async () => {
        setLoading(true);
        setError(null);
        await fetchTopExpense();
        try {
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) throw new Error('Usuario no autenticado');

            // Fetch from the VIEW
            const { data, error } = await supabase
                .from('v_estrategia_metas_detalle')
                .select('*')
                .eq('user_id', user.id);

            if (error) throw error;

            if (data) {
                const processedGoals: GoalWithIntelligence[] = data.map((g: any) => ({
                    ...g,
                    intelligence: calculateIntelligence(g)
                }));
                setGoals(processedGoals);
            }
        } catch (err: any) {
            console.error('Error fetching goal intelligence:', err);
            setError(err.message);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchGoals();
    }, [topExpenseCategory]);

    return { goals, loading, error, refresh: fetchGoals };
};
